import type { User } from "@/types/entities.ts";

export const contacts: User[] = [
  {
    id: "1",
    fullname: "Alice Johnson",
    email: "alice.johnson@example.com",
    avatar: null,
  },
  {
    id: "2",
    fullname: "Bob Smith",
    email: "bob.smith@example.com",
    avatar: null,
  },
  {
    id: "3",
    fullname: "Charlie Davis",
    email: "charlie.davis@example.com",
    avatar: null,
  },
  {
    id: "4",
    fullname: "Diana Martinez",
    email: "diana.martinez@example.com",
    avatar: null,
  },
  {
    id: "5",
    fullname: "Ethan Brown",
    email: "ethan.brown@example.com",
    avatar: null,
  },
  {
    id: "6",
    fullname: "Fiona Clark",
    email: "fiona.clark@example.com",
    avatar: null,
  },
  {
    id: "7",
    fullname: "George Lewis",
    email: "george.lewis@example.com",
    avatar: null,
  },
  {
    id: "8",
    fullname: "Hannah Walker",
    email: "hannah.walker@example.com",
    avatar: null,
  },
  {
    id: "9",
    fullname: "Ian Hall",
    email: "ian.hall@example.com",
    avatar: null,
  },
  {
    id: "10",
    fullname: "Julia Allen",
    email: "julia.allen@example.com",
    avatar: null,
  },
  {
    id: "11",
    fullname: "Kevin Young",
    email: "kevin.young@example.com",
    avatar: null,
  },
  {
    id: "12",
    fullname: "Laura King",
    email: "laura.king@example.com",
    avatar: null,
  },
  {
    id: "13",
    fullname: "Michael Wright",
    email: "michael.wright@example.com",
    avatar: null,
  },
  {
    id: "14",
    fullname: "Natalie Scott",
    email: "natalie.scott@example.com",
    avatar: null,
  },
  {
    id: "15",
    fullname: "Oliver Adams",
    email: "oliver.adams@example.com",
    avatar: null,
  },
  {
    id: "16",
    fullname: "Patricia Baker",
    email: "patricia.baker@example.com",
    avatar: null,
  },
  {
    id: "17",
    fullname: "Quentin Carter",
    email: "quentin.carter@example.com",
    avatar: null,
  },
  {
    id: "18",
    fullname: "Rachel Evans",
    email: "rachel.evans@example.com",
    avatar: null,
  },
  {
    id: "19",
    fullname: "Steven Foster",
    email: "steven.foster@example.com",
    avatar: null,
  },
  {
    id: "20",
    fullname: "Tina Green",
    email: "tina.green@example.com",
    avatar: null,
  },
  {
    id: "21",
    fullname: "Ulysses Harris",
    email: "ulysses.harris@example.com",
    avatar: null,
  },
  {
    id: "22",
    fullname: "Victoria Jenkins",
    email: "victoria.jenkins@example.com",
    avatar: null,
  },
  {
    id: "23",
    fullname: "William Moore",
    email: "william.moore@example.com",
    avatar: null,
  },
  {
    id: "24",
    fullname: "Xavier Nelson",
    email: "xavier.nelson@example.com",
    avatar: null,
  },
  {
    id: "25",
    fullname: "Yvonne Parker",
    email: "yvonne.parker@example.com",
    avatar: null,
  },
  {
    id: "26",
    fullname: "Zachary Reed",
    email: "zachary.reed@example.com",
    avatar: null,
  },
];
