import type { Patient } from "../../types/entities.ts";

export const patients: Patient[] = [
  {
    id: "1",
    fullname: "Ahmed Benali",
    email: "ahmed.benali@example.com",
    avatar: null,
    lastVisit: new Date("2026-02-12"),
    status: "active",
  },
  {
    id: "2",
    fullname: "Fatima Zahra Bensalem",
    email: "fatima.bensalem@example.com",
    avatar: null,
    lastVisit: new Date("2026-01-30"),
    status: "active",
  },
  {
    id: "3",
    fullname: "Yacine Boudiaf",
    email: "yacine.boudiaf@example.com",
    avatar: null,
    lastVisit: new Date("2025-12-10"),
    status: "inactive",
  },
  {
    id: "4",
    fullname: "Samira Haddad",
    email: "samira.haddad@example.com",
    avatar: null,
    lastVisit: new Date("2026-02-01"),
    status: "active",
  },
  {
    id: "5",
    fullname: "Karim Touati",
    email: "karim.touati@example.com",
    avatar: null,
    lastVisit: new Date("2025-11-18"),
    status: "inactive",
  },
  {
    id: "6",
    fullname: "Nadia Meziane",
    email: "nadia.meziane@example.com",
    avatar: null,
    lastVisit: new Date("2026-02-20"),
    status: "active",
  },
  {
    id: "7",
    fullname: "Mohamed Amine Cherif",
    email: "mohamed.cherif@example.com",
    avatar: null,
    lastVisit: new Date("2026-01-05"),
    status: "active",
  },
  {
    id: "8",
    fullname: "Amina Belkacem",
    email: "amina.belkacem@example.com",
    avatar: null,
    lastVisit: new Date("2025-10-22"),
    status: "inactive",
  },
  {
    id: "9",
    fullname: "Rachid Mansouri",
    email: "rachid.mansouri@example.com",
    avatar: null,
    lastVisit: new Date("2026-02-15"),
    status: "active",
  },
  {
    id: "10",
    fullname: "Lina Zerrouki",
    email: "lina.zerrouki@example.com",
    avatar: null,
    lastVisit: new Date("2026-01-28"),
    status: "active",
  },
];
