import type { Patient, PatientDetails } from "../../types/entities.ts";
import { BLOOD_TYPE, GENDER } from "../index.ts";

export const patients: Patient[] = [
  {
    id: "1",
    fullname: "Ahmed Benali",
    email: "ahmed.benali@example.com",
    phoneNumber: "0551 23 45 67",
    avatar: null,
    lastVisit: new Date("2026-02-12"),
    status: "active",
  },
  {
    id: "2",
    fullname: "Fatima Zahra Bensalem",
    email: "fatima.bensalem@example.com",
    phoneNumber: "0662 14 89 33",
    avatar: null,
    lastVisit: new Date("2026-01-30"),
    status: "active",
  },
  {
    id: "3",
    fullname: "Yacine Boudiaf",
    email: "yacine.boudiaf@example.com",
    phoneNumber: "0774 55 91 20",
    avatar: null,
    lastVisit: new Date("2025-12-10"),
    status: "inactive",
  },
  {
    id: "4",
    fullname: "Samira Haddad",
    email: "samira.haddad@example.com",
    phoneNumber: "0558 72 61 90",
    avatar: null,
    lastVisit: new Date("2026-02-01"),
    status: "active",
  },
  {
    id: "5",
    fullname: "Karim Touati",
    email: "karim.touati@example.com",
    phoneNumber: "0669 38 44 12",
    avatar: null,
    lastVisit: new Date("2025-11-18"),
    status: "inactive",
  },
  {
    id: "6",
    fullname: "Nadia Meziane",
    email: "nadia.meziane@example.com",
    phoneNumber: "0771 62 09 54",
    avatar: null,
    lastVisit: new Date("2026-02-20"),
    status: "active",
  },
  {
    id: "7",
    fullname: "Mohamed Amine Cherif",
    email: "mohamed.cherif@example.com",
    phoneNumber: "0553 40 17 86",
    avatar: null,
    lastVisit: new Date("2026-01-05"),
    status: "active",
  },
  {
    id: "8",
    fullname: "Amina Belkacem",
    email: "amina.belkacem@example.com",
    phoneNumber: "0664 29 73 11",
    avatar: null,
    lastVisit: new Date("2025-10-22"),
    status: "inactive",
  },
  {
    id: "9",
    fullname: "Rachid Mansouri",
    email: "rachid.mansouri@example.com",
    phoneNumber: "0776 81 22 45",
    avatar: null,
    lastVisit: new Date("2026-02-15"),
    status: "active",
  },
  {
    id: "10",
    fullname: "Lina Zerrouki",
    email: "lina.zerrouki@example.com",
    phoneNumber: "0557 90 36 28",
    avatar: null,
    lastVisit: new Date("2026-01-28"),
    status: "active",
  },
];

const patientDetailsData = [
  {
    age: 34,
    gender: GENDER.MALE,
    nationalId: "DZ19890321",
    address: "Oran, Algeria",
    bloodType: BLOOD_TYPE.O_POS,
    allergies: ["Penicillin"],
    chronicConditions: ["Hypertension"],
  },
  {
    age: 29,
    gender: GENDER.FEMALE,
    nationalId: "DZ19960712",
    address: "Algiers, Algeria",
    bloodType: BLOOD_TYPE.A_POS,
    allergies: ["Peanuts"],
    chronicConditions: [],
  },
  {
    age: 41,
    gender: GENDER.MALE,
    nationalId: "DZ19840115",
    address: "Constantine, Algeria",
    bloodType: BLOOD_TYPE.B_POS,
    allergies: [],
    chronicConditions: ["Asthma"],
  },
  {
    age: 36,
    gender: GENDER.FEMALE,
    nationalId: "DZ19900108",
    address: "Oran, Algeria",
    bloodType: BLOOD_TYPE.AB_POS,
    allergies: ["Dust"],
    chronicConditions: [],
  },
  {
    age: 52,
    gender: GENDER.MALE,
    nationalId: "DZ19731002",
    address: "Tlemcen, Algeria",
    bloodType: BLOOD_TYPE.O_NEG,
    allergies: [],
    chronicConditions: ["Diabetes Type 2"],
  },
  {
    age: 27,
    gender: GENDER.FEMALE,
    nationalId: "DZ19981130",
    address: "Mostaganem, Algeria",
    bloodType: BLOOD_TYPE.B_NEG,
    allergies: ["Shellfish"],
    chronicConditions: [],
  },
  {
    age: 31,
    gender: GENDER.MALE,
    nationalId: "DZ19940319",
    address: "Oran, Algeria",
    bloodType: BLOOD_TYPE.A_POS,
    allergies: [],
    chronicConditions: ["Migraine"],
  },
  {
    age: 45,
    gender: GENDER.FEMALE,
    nationalId: "DZ19800427",
    address: "Sidi Bel Abbès, Algeria",
    bloodType: BLOOD_TYPE.AB_NEG,
    allergies: ["Latex"],
    chronicConditions: ["Arthritis"],
  },
  {
    age: 38,
    gender: GENDER.MALE,
    nationalId: "DZ19870714",
    address: "Oran, Algeria",
    bloodType: BLOOD_TYPE.O_POS,
    allergies: [],
    chronicConditions: [],
  },
  {
    age: 24,
    gender: GENDER.FEMALE,
    nationalId: "DZ20011205",
    address: "Algiers, Algeria",
    bloodType: BLOOD_TYPE.A_POS,
    allergies: ["Pollen"],
    chronicConditions: [],
  },
];

export const patientsWithDetails: PatientDetails[] = patients.map((p, i) => ({
  ...p,
  ...patientDetailsData[i],
}));
