import { GENDER, ROLE } from "@/constants/index.ts";
import type { DoctorProfile } from "@/types/entities.ts";
import { users } from "../auth.ts";

export const profiles: DoctorProfile[] = [
  {
    ...users[0],
    bio: "Docteur généraliste, spécialisé dans le suivi médical et les consultations de routine.",
  },
  {
    id: "1",
    fullname: "Yacine Belkacem",
    email: "yacine.belkacem@example.dz",
    phoneNumber: "0551 23 45 67",
    avatar: null,
    age: 27,
    address: null,
    gender: GENDER.MALE,
    nationalId: "DZ-199701123456",
    role: ROLE.DOCTOR,
    bio: "Médecin généraliste à Oran, spécialisé dans le diagnostic et le traitement des maladies courantes.",
  },
  {
    id: "2",
    fullname: "Amira Bouzid",
    email: "amira.bouzid@example.dz",
    phoneNumber: "0662 14 89 33",
    avatar: null,
    age: 24,
    address: null,
    gender: GENDER.FEMALE,
    nationalId: "DZ-199903987654",
    role: ROLE.DOCTOR,
    bio: "Cardiologue, passionnée par la prévention et le suivi des maladies cardiovasculaires.",
  },
  {
    id: "3",
    fullname: "Karim Saidi",
    email: "karim.saidi@example.dz",
    phoneNumber: "0774 55 91 20",
    avatar: null,
    age: 30,
    address: null,
    gender: GENDER.MALE,
    nationalId: "DZ-199401556789",
    role: ROLE.DOCTOR,
    bio: "Pédiatre spécialisé dans le suivi de la santé des enfants et adolescents.",
  },
  {
    id: "4",
    fullname: "Nour El Houda Farhi",
    email: "nour.farhi@example.dz",
    phoneNumber: "0559 88 12 44",
    avatar: null,
    age: 26,
    address: null,
    gender: GENDER.FEMALE,
    nationalId: "DZ-199801223344",
    role: ROLE.DOCTOR,
    bio: "Dermatologue, experte en soins de la peau et traitement des affections cutanées.",
  },
  {
    id: "5",
    fullname: "Mehdi Khelladi",
    email: "mehdi.khelladi@example.dz",
    phoneNumber: "0655 77 33 10",
    avatar: null,
    age: 28,
    address: null,
    gender: GENDER.MALE,
    nationalId: "DZ-199601998877",
    role: ROLE.DOCTOR,
    bio: "Médecin spécialiste avec expérience en diagnostic avancé et suivi des pathologies complexes.",
  },
];
