/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppPlanningRouteImport } from './routes/_app/planning'
import { Route as AppPatientsRouteImport } from './routes/_app/patients'
import { Route as AppChatRouteImport } from './routes/_app/chat'
import { Route as AuthRegisterIndexRouteImport } from './routes/_auth/register/index'
import { Route as AuthRegisterPatientRouteImport } from './routes/_auth/register/patient'
import { Route as AuthRegisterDoctorRouteImport } from './routes/_auth/register/doctor'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPlanningRoute = AppPlanningRouteImport.update({
  id: '/planning',
  path: '/planning',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPatientsRoute = AppPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthRegisterIndexRoute = AuthRegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRegisterPatientRoute = AuthRegisterPatientRouteImport.update({
  id: '/register/patient',
  path: '/register/patient',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRegisterDoctorRoute = AuthRegisterDoctorRouteImport.update({
  id: '/register/doctor',
  path: '/register/doctor',
  getParentRoute: () => AuthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/chat': typeof AppChatRoute
  '/patients': typeof AppPatientsRoute
  '/planning': typeof AppPlanningRoute
  '/settings': typeof AppSettingsRoute
  '/login': typeof AuthLoginRoute
  '/register/doctor': typeof AuthRegisterDoctorRoute
  '/register/patient': typeof AuthRegisterPatientRoute
  '/register/': typeof AuthRegisterIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/chat': typeof AppChatRoute
  '/patients': typeof AppPatientsRoute
  '/planning': typeof AppPlanningRoute
  '/settings': typeof AppSettingsRoute
  '/login': typeof AuthLoginRoute
  '/register/doctor': typeof AuthRegisterDoctorRoute
  '/register/patient': typeof AuthRegisterPatientRoute
  '/register': typeof AuthRegisterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_app/chat': typeof AppChatRoute
  '/_app/patients': typeof AppPatientsRoute
  '/_app/planning': typeof AppPlanningRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_app/': typeof AppIndexRoute
  '/_auth/register/doctor': typeof AuthRegisterDoctorRoute
  '/_auth/register/patient': typeof AuthRegisterPatientRoute
  '/_auth/register/': typeof AuthRegisterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/patients'
    | '/planning'
    | '/settings'
    | '/login'
    | '/register/doctor'
    | '/register/patient'
    | '/register/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/patients'
    | '/planning'
    | '/settings'
    | '/login'
    | '/register/doctor'
    | '/register/patient'
    | '/register'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_app/chat'
    | '/_app/patients'
    | '/_app/planning'
    | '/_app/settings'
    | '/_auth/login'
    | '/_app/'
    | '/_auth/register/doctor'
    | '/_auth/register/patient'
    | '/_auth/register/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/planning': {
      id: '/_app/planning'
      path: '/planning'
      fullPath: '/planning'
      preLoaderRoute: typeof AppPlanningRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/patients': {
      id: '/_app/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof AppPatientsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_auth/register/': {
      id: '/_auth/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof AuthRegisterIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/register/patient': {
      id: '/_auth/register/patient'
      path: '/register/patient'
      fullPath: '/register/patient'
      preLoaderRoute: typeof AuthRegisterPatientRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/register/doctor': {
      id: '/_auth/register/doctor'
      path: '/register/doctor'
      fullPath: '/register/doctor'
      preLoaderRoute: typeof AuthRegisterDoctorRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppChatRoute: typeof AppChatRoute
  AppPatientsRoute: typeof AppPatientsRoute
  AppPlanningRoute: typeof AppPlanningRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppChatRoute: AppChatRoute,
  AppPatientsRoute: AppPatientsRoute,
  AppPlanningRoute: AppPlanningRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterDoctorRoute: typeof AuthRegisterDoctorRoute
  AuthRegisterPatientRoute: typeof AuthRegisterPatientRoute
  AuthRegisterIndexRoute: typeof AuthRegisterIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterDoctorRoute: AuthRegisterDoctorRoute,
  AuthRegisterPatientRoute: AuthRegisterPatientRoute,
  AuthRegisterIndexRoute: AuthRegisterIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
