/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as PublicAuthRouteRouteImport } from './routes/_public/_auth/route'
import { Route as ProtectedDoctorRouteRouteImport } from './routes/_protected/_doctor/route'
import { Route as ProtectedAdminRouteRouteImport } from './routes/_protected/_admin/route'
import { Route as PublicAuthLoginRouteImport } from './routes/_public/_auth/login'
import { Route as ProtectedSharedAppRouteRouteImport } from './routes/_protected/_shared/_app/route'
import { Route as ProtectedDoctorPatientsRouteRouteImport } from './routes/_protected/_doctor/patients/route'
import { Route as ProtectedDoctorAppRouteRouteImport } from './routes/_protected/_doctor/_app/route'
import { Route as ProtectedAdminAppRouteRouteImport } from './routes/_protected/_admin/_app/route'
import { Route as PublicAuthRegisterIndexRouteImport } from './routes/_public/_auth/register/index'
import { Route as PublicAuthRegisterPatientRouteImport } from './routes/_public/_auth/register/patient'
import { Route as PublicAuthRegisterDoctorRouteImport } from './routes/_public/_auth/register/doctor'
import { Route as ProtectedDoctorAppPlanningRouteImport } from './routes/_protected/_doctor/_app/planning'
import { Route as ProtectedDoctorAppPatientsRouteImport } from './routes/_protected/_doctor/_app/patients'
import { Route as ProtectedDoctorAppChatRouteImport } from './routes/_protected/_doctor/_app/chat'
import { Route as ProtectedAdminAppPatRouteImport } from './routes/_protected/_admin/_app/pat'
import { Route as ProtectedAdminAppDoctorsRouteImport } from './routes/_protected/_admin/_app/doctors'
import { Route as ProtectedSharedAppSettingsRouteRouteImport } from './routes/_protected/_shared/_app/settings/route'
import { Route as ProtectedDoctorPatientsPatientIdRouteRouteImport } from './routes/_protected/_doctor/patients/$patientId/route'
import { Route as ProtectedSharedAppSettingsIndexRouteImport } from './routes/_protected/_shared/_app/settings/index'
import { Route as ProtectedSharedAppDashboardIndexRouteImport } from './routes/_protected/_shared/_app/_dashboard/index'
import { Route as ProtectedDoctorPatientsPatientIdIndexRouteImport } from './routes/_protected/_doctor/patients/$patientId/index'
import { Route as ProtectedSharedAppSettingsAccountRouteImport } from './routes/_protected/_shared/_app/settings/account'
import { Route as ProtectedDoctorPatientsPatientIdReportRouteImport } from './routes/_protected/_doctor/patients/$patientId/report'
import { Route as ProtectedDoctorPatientsPatientIdProfileRouteImport } from './routes/_protected/_doctor/patients/$patientId/profile'
import { Route as ProtectedDoctorPatientsPatientIdFileRouteImport } from './routes/_protected/_doctor/patients/$patientId/file'
import { Route as ProtectedDoctorPatientsPatientIdDraftsRouteImport } from './routes/_protected/_doctor/patients/$patientId/drafts'

const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicAuthRouteRoute = PublicAuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => PublicRouteRoute,
} as any)
const ProtectedDoctorRouteRoute = ProtectedDoctorRouteRouteImport.update({
  id: '/_doctor',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedAdminRouteRoute = ProtectedAdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const PublicAuthLoginRoute = PublicAuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicAuthRouteRoute,
} as any)
const ProtectedSharedAppRouteRoute = ProtectedSharedAppRouteRouteImport.update({
  id: '/_shared/_app',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedDoctorPatientsRouteRoute =
  ProtectedDoctorPatientsRouteRouteImport.update({
    id: '/patients',
    path: '/patients',
    getParentRoute: () => ProtectedDoctorRouteRoute,
  } as any)
const ProtectedDoctorAppRouteRoute = ProtectedDoctorAppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => ProtectedDoctorRouteRoute,
} as any)
const ProtectedAdminAppRouteRoute = ProtectedAdminAppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => ProtectedAdminRouteRoute,
} as any)
const PublicAuthRegisterIndexRoute = PublicAuthRegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => PublicAuthRouteRoute,
} as any)
const PublicAuthRegisterPatientRoute =
  PublicAuthRegisterPatientRouteImport.update({
    id: '/register/patient',
    path: '/register/patient',
    getParentRoute: () => PublicAuthRouteRoute,
  } as any)
const PublicAuthRegisterDoctorRoute =
  PublicAuthRegisterDoctorRouteImport.update({
    id: '/register/doctor',
    path: '/register/doctor',
    getParentRoute: () => PublicAuthRouteRoute,
  } as any)
const ProtectedDoctorAppPlanningRoute =
  ProtectedDoctorAppPlanningRouteImport.update({
    id: '/planning',
    path: '/planning',
    getParentRoute: () => ProtectedDoctorAppRouteRoute,
  } as any)
const ProtectedDoctorAppPatientsRoute =
  ProtectedDoctorAppPatientsRouteImport.update({
    id: '/patients',
    path: '/patients',
    getParentRoute: () => ProtectedDoctorAppRouteRoute,
  } as any)
const ProtectedDoctorAppChatRoute = ProtectedDoctorAppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => ProtectedDoctorAppRouteRoute,
} as any)
const ProtectedAdminAppPatRoute = ProtectedAdminAppPatRouteImport.update({
  id: '/pat',
  path: '/pat',
  getParentRoute: () => ProtectedAdminAppRouteRoute,
} as any)
const ProtectedAdminAppDoctorsRoute =
  ProtectedAdminAppDoctorsRouteImport.update({
    id: '/doctors',
    path: '/doctors',
    getParentRoute: () => ProtectedAdminAppRouteRoute,
  } as any)
const ProtectedSharedAppSettingsRouteRoute =
  ProtectedSharedAppSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ProtectedSharedAppRouteRoute,
  } as any)
const ProtectedDoctorPatientsPatientIdRouteRoute =
  ProtectedDoctorPatientsPatientIdRouteRouteImport.update({
    id: '/$patientId',
    path: '/$patientId',
    getParentRoute: () => ProtectedDoctorPatientsRouteRoute,
  } as any)
const ProtectedSharedAppSettingsIndexRoute =
  ProtectedSharedAppSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedSharedAppSettingsRouteRoute,
  } as any)
const ProtectedSharedAppDashboardIndexRoute =
  ProtectedSharedAppDashboardIndexRouteImport.update({
    id: '/_dashboard/',
    path: '/',
    getParentRoute: () => ProtectedSharedAppRouteRoute,
  } as any)
const ProtectedDoctorPatientsPatientIdIndexRoute =
  ProtectedDoctorPatientsPatientIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedDoctorPatientsPatientIdRouteRoute,
  } as any)
const ProtectedSharedAppSettingsAccountRoute =
  ProtectedSharedAppSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => ProtectedSharedAppSettingsRouteRoute,
  } as any)
const ProtectedDoctorPatientsPatientIdReportRoute =
  ProtectedDoctorPatientsPatientIdReportRouteImport.update({
    id: '/report',
    path: '/report',
    getParentRoute: () => ProtectedDoctorPatientsPatientIdRouteRoute,
  } as any)
const ProtectedDoctorPatientsPatientIdProfileRoute =
  ProtectedDoctorPatientsPatientIdProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => ProtectedDoctorPatientsPatientIdRouteRoute,
  } as any)
const ProtectedDoctorPatientsPatientIdFileRoute =
  ProtectedDoctorPatientsPatientIdFileRouteImport.update({
    id: '/file',
    path: '/file',
    getParentRoute: () => ProtectedDoctorPatientsPatientIdRouteRoute,
  } as any)
const ProtectedDoctorPatientsPatientIdDraftsRoute =
  ProtectedDoctorPatientsPatientIdDraftsRouteImport.update({
    id: '/drafts',
    path: '/drafts',
    getParentRoute: () => ProtectedDoctorPatientsPatientIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedSharedAppDashboardIndexRoute
  '/patients': typeof ProtectedDoctorAppPatientsRoute
  '/login': typeof PublicAuthLoginRoute
  '/patients/$patientId': typeof ProtectedDoctorPatientsPatientIdRouteRouteWithChildren
  '/settings': typeof ProtectedSharedAppSettingsRouteRouteWithChildren
  '/doctors': typeof ProtectedAdminAppDoctorsRoute
  '/pat': typeof ProtectedAdminAppPatRoute
  '/chat': typeof ProtectedDoctorAppChatRoute
  '/planning': typeof ProtectedDoctorAppPlanningRoute
  '/register/doctor': typeof PublicAuthRegisterDoctorRoute
  '/register/patient': typeof PublicAuthRegisterPatientRoute
  '/register/': typeof PublicAuthRegisterIndexRoute
  '/patients/$patientId/drafts': typeof ProtectedDoctorPatientsPatientIdDraftsRoute
  '/patients/$patientId/file': typeof ProtectedDoctorPatientsPatientIdFileRoute
  '/patients/$patientId/profile': typeof ProtectedDoctorPatientsPatientIdProfileRoute
  '/patients/$patientId/report': typeof ProtectedDoctorPatientsPatientIdReportRoute
  '/settings/account': typeof ProtectedSharedAppSettingsAccountRoute
  '/patients/$patientId/': typeof ProtectedDoctorPatientsPatientIdIndexRoute
  '/settings/': typeof ProtectedSharedAppSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof ProtectedSharedAppDashboardIndexRoute
  '/patients': typeof ProtectedDoctorAppPatientsRoute
  '/login': typeof PublicAuthLoginRoute
  '/doctors': typeof ProtectedAdminAppDoctorsRoute
  '/pat': typeof ProtectedAdminAppPatRoute
  '/chat': typeof ProtectedDoctorAppChatRoute
  '/planning': typeof ProtectedDoctorAppPlanningRoute
  '/register/doctor': typeof PublicAuthRegisterDoctorRoute
  '/register/patient': typeof PublicAuthRegisterPatientRoute
  '/register': typeof PublicAuthRegisterIndexRoute
  '/patients/$patientId/drafts': typeof ProtectedDoctorPatientsPatientIdDraftsRoute
  '/patients/$patientId/file': typeof ProtectedDoctorPatientsPatientIdFileRoute
  '/patients/$patientId/profile': typeof ProtectedDoctorPatientsPatientIdProfileRoute
  '/patients/$patientId/report': typeof ProtectedDoctorPatientsPatientIdReportRoute
  '/settings/account': typeof ProtectedSharedAppSettingsAccountRoute
  '/patients/$patientId': typeof ProtectedDoctorPatientsPatientIdIndexRoute
  '/settings': typeof ProtectedSharedAppSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/_protected/_admin': typeof ProtectedAdminRouteRouteWithChildren
  '/_protected/_doctor': typeof ProtectedDoctorRouteRouteWithChildren
  '/_public/_auth': typeof PublicAuthRouteRouteWithChildren
  '/_protected/_admin/_app': typeof ProtectedAdminAppRouteRouteWithChildren
  '/_protected/_doctor/_app': typeof ProtectedDoctorAppRouteRouteWithChildren
  '/_protected/_doctor/patients': typeof ProtectedDoctorPatientsRouteRouteWithChildren
  '/_protected/_shared/_app': typeof ProtectedSharedAppRouteRouteWithChildren
  '/_public/_auth/login': typeof PublicAuthLoginRoute
  '/_protected/_doctor/patients/$patientId': typeof ProtectedDoctorPatientsPatientIdRouteRouteWithChildren
  '/_protected/_shared/_app/settings': typeof ProtectedSharedAppSettingsRouteRouteWithChildren
  '/_protected/_admin/_app/doctors': typeof ProtectedAdminAppDoctorsRoute
  '/_protected/_admin/_app/pat': typeof ProtectedAdminAppPatRoute
  '/_protected/_doctor/_app/chat': typeof ProtectedDoctorAppChatRoute
  '/_protected/_doctor/_app/patients': typeof ProtectedDoctorAppPatientsRoute
  '/_protected/_doctor/_app/planning': typeof ProtectedDoctorAppPlanningRoute
  '/_public/_auth/register/doctor': typeof PublicAuthRegisterDoctorRoute
  '/_public/_auth/register/patient': typeof PublicAuthRegisterPatientRoute
  '/_public/_auth/register/': typeof PublicAuthRegisterIndexRoute
  '/_protected/_doctor/patients/$patientId/drafts': typeof ProtectedDoctorPatientsPatientIdDraftsRoute
  '/_protected/_doctor/patients/$patientId/file': typeof ProtectedDoctorPatientsPatientIdFileRoute
  '/_protected/_doctor/patients/$patientId/profile': typeof ProtectedDoctorPatientsPatientIdProfileRoute
  '/_protected/_doctor/patients/$patientId/report': typeof ProtectedDoctorPatientsPatientIdReportRoute
  '/_protected/_shared/_app/settings/account': typeof ProtectedSharedAppSettingsAccountRoute
  '/_protected/_doctor/patients/$patientId/': typeof ProtectedDoctorPatientsPatientIdIndexRoute
  '/_protected/_shared/_app/_dashboard/': typeof ProtectedSharedAppDashboardIndexRoute
  '/_protected/_shared/_app/settings/': typeof ProtectedSharedAppSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/patients'
    | '/login'
    | '/patients/$patientId'
    | '/settings'
    | '/doctors'
    | '/pat'
    | '/chat'
    | '/planning'
    | '/register/doctor'
    | '/register/patient'
    | '/register/'
    | '/patients/$patientId/drafts'
    | '/patients/$patientId/file'
    | '/patients/$patientId/profile'
    | '/patients/$patientId/report'
    | '/settings/account'
    | '/patients/$patientId/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/patients'
    | '/login'
    | '/doctors'
    | '/pat'
    | '/chat'
    | '/planning'
    | '/register/doctor'
    | '/register/patient'
    | '/register'
    | '/patients/$patientId/drafts'
    | '/patients/$patientId/file'
    | '/patients/$patientId/profile'
    | '/patients/$patientId/report'
    | '/settings/account'
    | '/patients/$patientId'
    | '/settings'
  id:
    | '__root__'
    | '/_protected'
    | '/_public'
    | '/_protected/_admin'
    | '/_protected/_doctor'
    | '/_public/_auth'
    | '/_protected/_admin/_app'
    | '/_protected/_doctor/_app'
    | '/_protected/_doctor/patients'
    | '/_protected/_shared/_app'
    | '/_public/_auth/login'
    | '/_protected/_doctor/patients/$patientId'
    | '/_protected/_shared/_app/settings'
    | '/_protected/_admin/_app/doctors'
    | '/_protected/_admin/_app/pat'
    | '/_protected/_doctor/_app/chat'
    | '/_protected/_doctor/_app/patients'
    | '/_protected/_doctor/_app/planning'
    | '/_public/_auth/register/doctor'
    | '/_public/_auth/register/patient'
    | '/_public/_auth/register/'
    | '/_protected/_doctor/patients/$patientId/drafts'
    | '/_protected/_doctor/patients/$patientId/file'
    | '/_protected/_doctor/patients/$patientId/profile'
    | '/_protected/_doctor/patients/$patientId/report'
    | '/_protected/_shared/_app/settings/account'
    | '/_protected/_doctor/patients/$patientId/'
    | '/_protected/_shared/_app/_dashboard/'
    | '/_protected/_shared/_app/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/_auth': {
      id: '/_public/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicAuthRouteRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_protected/_doctor': {
      id: '/_protected/_doctor'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedDoctorRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/_admin': {
      id: '/_protected/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedAdminRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_public/_auth/login': {
      id: '/_public/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicAuthLoginRouteImport
      parentRoute: typeof PublicAuthRouteRoute
    }
    '/_protected/_shared/_app': {
      id: '/_protected/_shared/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedSharedAppRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/_doctor/patients': {
      id: '/_protected/_doctor/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof ProtectedDoctorPatientsRouteRouteImport
      parentRoute: typeof ProtectedDoctorRouteRoute
    }
    '/_protected/_doctor/_app': {
      id: '/_protected/_doctor/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedDoctorAppRouteRouteImport
      parentRoute: typeof ProtectedDoctorRouteRoute
    }
    '/_protected/_admin/_app': {
      id: '/_protected/_admin/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedAdminAppRouteRouteImport
      parentRoute: typeof ProtectedAdminRouteRoute
    }
    '/_public/_auth/register/': {
      id: '/_public/_auth/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof PublicAuthRegisterIndexRouteImport
      parentRoute: typeof PublicAuthRouteRoute
    }
    '/_public/_auth/register/patient': {
      id: '/_public/_auth/register/patient'
      path: '/register/patient'
      fullPath: '/register/patient'
      preLoaderRoute: typeof PublicAuthRegisterPatientRouteImport
      parentRoute: typeof PublicAuthRouteRoute
    }
    '/_public/_auth/register/doctor': {
      id: '/_public/_auth/register/doctor'
      path: '/register/doctor'
      fullPath: '/register/doctor'
      preLoaderRoute: typeof PublicAuthRegisterDoctorRouteImport
      parentRoute: typeof PublicAuthRouteRoute
    }
    '/_protected/_doctor/_app/planning': {
      id: '/_protected/_doctor/_app/planning'
      path: '/planning'
      fullPath: '/planning'
      preLoaderRoute: typeof ProtectedDoctorAppPlanningRouteImport
      parentRoute: typeof ProtectedDoctorAppRouteRoute
    }
    '/_protected/_doctor/_app/patients': {
      id: '/_protected/_doctor/_app/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof ProtectedDoctorAppPatientsRouteImport
      parentRoute: typeof ProtectedDoctorAppRouteRoute
    }
    '/_protected/_doctor/_app/chat': {
      id: '/_protected/_doctor/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ProtectedDoctorAppChatRouteImport
      parentRoute: typeof ProtectedDoctorAppRouteRoute
    }
    '/_protected/_admin/_app/pat': {
      id: '/_protected/_admin/_app/pat'
      path: '/pat'
      fullPath: '/pat'
      preLoaderRoute: typeof ProtectedAdminAppPatRouteImport
      parentRoute: typeof ProtectedAdminAppRouteRoute
    }
    '/_protected/_admin/_app/doctors': {
      id: '/_protected/_admin/_app/doctors'
      path: '/doctors'
      fullPath: '/doctors'
      preLoaderRoute: typeof ProtectedAdminAppDoctorsRouteImport
      parentRoute: typeof ProtectedAdminAppRouteRoute
    }
    '/_protected/_shared/_app/settings': {
      id: '/_protected/_shared/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSharedAppSettingsRouteRouteImport
      parentRoute: typeof ProtectedSharedAppRouteRoute
    }
    '/_protected/_doctor/patients/$patientId': {
      id: '/_protected/_doctor/patients/$patientId'
      path: '/$patientId'
      fullPath: '/patients/$patientId'
      preLoaderRoute: typeof ProtectedDoctorPatientsPatientIdRouteRouteImport
      parentRoute: typeof ProtectedDoctorPatientsRouteRoute
    }
    '/_protected/_shared/_app/settings/': {
      id: '/_protected/_shared/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof ProtectedSharedAppSettingsIndexRouteImport
      parentRoute: typeof ProtectedSharedAppSettingsRouteRoute
    }
    '/_protected/_shared/_app/_dashboard/': {
      id: '/_protected/_shared/_app/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedSharedAppDashboardIndexRouteImport
      parentRoute: typeof ProtectedSharedAppRouteRoute
    }
    '/_protected/_doctor/patients/$patientId/': {
      id: '/_protected/_doctor/patients/$patientId/'
      path: '/'
      fullPath: '/patients/$patientId/'
      preLoaderRoute: typeof ProtectedDoctorPatientsPatientIdIndexRouteImport
      parentRoute: typeof ProtectedDoctorPatientsPatientIdRouteRoute
    }
    '/_protected/_shared/_app/settings/account': {
      id: '/_protected/_shared/_app/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof ProtectedSharedAppSettingsAccountRouteImport
      parentRoute: typeof ProtectedSharedAppSettingsRouteRoute
    }
    '/_protected/_doctor/patients/$patientId/report': {
      id: '/_protected/_doctor/patients/$patientId/report'
      path: '/report'
      fullPath: '/patients/$patientId/report'
      preLoaderRoute: typeof ProtectedDoctorPatientsPatientIdReportRouteImport
      parentRoute: typeof ProtectedDoctorPatientsPatientIdRouteRoute
    }
    '/_protected/_doctor/patients/$patientId/profile': {
      id: '/_protected/_doctor/patients/$patientId/profile'
      path: '/profile'
      fullPath: '/patients/$patientId/profile'
      preLoaderRoute: typeof ProtectedDoctorPatientsPatientIdProfileRouteImport
      parentRoute: typeof ProtectedDoctorPatientsPatientIdRouteRoute
    }
    '/_protected/_doctor/patients/$patientId/file': {
      id: '/_protected/_doctor/patients/$patientId/file'
      path: '/file'
      fullPath: '/patients/$patientId/file'
      preLoaderRoute: typeof ProtectedDoctorPatientsPatientIdFileRouteImport
      parentRoute: typeof ProtectedDoctorPatientsPatientIdRouteRoute
    }
    '/_protected/_doctor/patients/$patientId/drafts': {
      id: '/_protected/_doctor/patients/$patientId/drafts'
      path: '/drafts'
      fullPath: '/patients/$patientId/drafts'
      preLoaderRoute: typeof ProtectedDoctorPatientsPatientIdDraftsRouteImport
      parentRoute: typeof ProtectedDoctorPatientsPatientIdRouteRoute
    }
  }
}

interface ProtectedAdminAppRouteRouteChildren {
  ProtectedAdminAppDoctorsRoute: typeof ProtectedAdminAppDoctorsRoute
  ProtectedAdminAppPatRoute: typeof ProtectedAdminAppPatRoute
}

const ProtectedAdminAppRouteRouteChildren: ProtectedAdminAppRouteRouteChildren =
  {
    ProtectedAdminAppDoctorsRoute: ProtectedAdminAppDoctorsRoute,
    ProtectedAdminAppPatRoute: ProtectedAdminAppPatRoute,
  }

const ProtectedAdminAppRouteRouteWithChildren =
  ProtectedAdminAppRouteRoute._addFileChildren(
    ProtectedAdminAppRouteRouteChildren,
  )

interface ProtectedAdminRouteRouteChildren {
  ProtectedAdminAppRouteRoute: typeof ProtectedAdminAppRouteRouteWithChildren
}

const ProtectedAdminRouteRouteChildren: ProtectedAdminRouteRouteChildren = {
  ProtectedAdminAppRouteRoute: ProtectedAdminAppRouteRouteWithChildren,
}

const ProtectedAdminRouteRouteWithChildren =
  ProtectedAdminRouteRoute._addFileChildren(ProtectedAdminRouteRouteChildren)

interface ProtectedDoctorAppRouteRouteChildren {
  ProtectedDoctorAppChatRoute: typeof ProtectedDoctorAppChatRoute
  ProtectedDoctorAppPatientsRoute: typeof ProtectedDoctorAppPatientsRoute
  ProtectedDoctorAppPlanningRoute: typeof ProtectedDoctorAppPlanningRoute
}

const ProtectedDoctorAppRouteRouteChildren: ProtectedDoctorAppRouteRouteChildren =
  {
    ProtectedDoctorAppChatRoute: ProtectedDoctorAppChatRoute,
    ProtectedDoctorAppPatientsRoute: ProtectedDoctorAppPatientsRoute,
    ProtectedDoctorAppPlanningRoute: ProtectedDoctorAppPlanningRoute,
  }

const ProtectedDoctorAppRouteRouteWithChildren =
  ProtectedDoctorAppRouteRoute._addFileChildren(
    ProtectedDoctorAppRouteRouteChildren,
  )

interface ProtectedDoctorPatientsPatientIdRouteRouteChildren {
  ProtectedDoctorPatientsPatientIdDraftsRoute: typeof ProtectedDoctorPatientsPatientIdDraftsRoute
  ProtectedDoctorPatientsPatientIdFileRoute: typeof ProtectedDoctorPatientsPatientIdFileRoute
  ProtectedDoctorPatientsPatientIdProfileRoute: typeof ProtectedDoctorPatientsPatientIdProfileRoute
  ProtectedDoctorPatientsPatientIdReportRoute: typeof ProtectedDoctorPatientsPatientIdReportRoute
  ProtectedDoctorPatientsPatientIdIndexRoute: typeof ProtectedDoctorPatientsPatientIdIndexRoute
}

const ProtectedDoctorPatientsPatientIdRouteRouteChildren: ProtectedDoctorPatientsPatientIdRouteRouteChildren =
  {
    ProtectedDoctorPatientsPatientIdDraftsRoute:
      ProtectedDoctorPatientsPatientIdDraftsRoute,
    ProtectedDoctorPatientsPatientIdFileRoute:
      ProtectedDoctorPatientsPatientIdFileRoute,
    ProtectedDoctorPatientsPatientIdProfileRoute:
      ProtectedDoctorPatientsPatientIdProfileRoute,
    ProtectedDoctorPatientsPatientIdReportRoute:
      ProtectedDoctorPatientsPatientIdReportRoute,
    ProtectedDoctorPatientsPatientIdIndexRoute:
      ProtectedDoctorPatientsPatientIdIndexRoute,
  }

const ProtectedDoctorPatientsPatientIdRouteRouteWithChildren =
  ProtectedDoctorPatientsPatientIdRouteRoute._addFileChildren(
    ProtectedDoctorPatientsPatientIdRouteRouteChildren,
  )

interface ProtectedDoctorPatientsRouteRouteChildren {
  ProtectedDoctorPatientsPatientIdRouteRoute: typeof ProtectedDoctorPatientsPatientIdRouteRouteWithChildren
}

const ProtectedDoctorPatientsRouteRouteChildren: ProtectedDoctorPatientsRouteRouteChildren =
  {
    ProtectedDoctorPatientsPatientIdRouteRoute:
      ProtectedDoctorPatientsPatientIdRouteRouteWithChildren,
  }

const ProtectedDoctorPatientsRouteRouteWithChildren =
  ProtectedDoctorPatientsRouteRoute._addFileChildren(
    ProtectedDoctorPatientsRouteRouteChildren,
  )

interface ProtectedDoctorRouteRouteChildren {
  ProtectedDoctorAppRouteRoute: typeof ProtectedDoctorAppRouteRouteWithChildren
  ProtectedDoctorPatientsRouteRoute: typeof ProtectedDoctorPatientsRouteRouteWithChildren
}

const ProtectedDoctorRouteRouteChildren: ProtectedDoctorRouteRouteChildren = {
  ProtectedDoctorAppRouteRoute: ProtectedDoctorAppRouteRouteWithChildren,
  ProtectedDoctorPatientsRouteRoute:
    ProtectedDoctorPatientsRouteRouteWithChildren,
}

const ProtectedDoctorRouteRouteWithChildren =
  ProtectedDoctorRouteRoute._addFileChildren(ProtectedDoctorRouteRouteChildren)

interface ProtectedSharedAppSettingsRouteRouteChildren {
  ProtectedSharedAppSettingsAccountRoute: typeof ProtectedSharedAppSettingsAccountRoute
  ProtectedSharedAppSettingsIndexRoute: typeof ProtectedSharedAppSettingsIndexRoute
}

const ProtectedSharedAppSettingsRouteRouteChildren: ProtectedSharedAppSettingsRouteRouteChildren =
  {
    ProtectedSharedAppSettingsAccountRoute:
      ProtectedSharedAppSettingsAccountRoute,
    ProtectedSharedAppSettingsIndexRoute: ProtectedSharedAppSettingsIndexRoute,
  }

const ProtectedSharedAppSettingsRouteRouteWithChildren =
  ProtectedSharedAppSettingsRouteRoute._addFileChildren(
    ProtectedSharedAppSettingsRouteRouteChildren,
  )

interface ProtectedSharedAppRouteRouteChildren {
  ProtectedSharedAppSettingsRouteRoute: typeof ProtectedSharedAppSettingsRouteRouteWithChildren
  ProtectedSharedAppDashboardIndexRoute: typeof ProtectedSharedAppDashboardIndexRoute
}

const ProtectedSharedAppRouteRouteChildren: ProtectedSharedAppRouteRouteChildren =
  {
    ProtectedSharedAppSettingsRouteRoute:
      ProtectedSharedAppSettingsRouteRouteWithChildren,
    ProtectedSharedAppDashboardIndexRoute:
      ProtectedSharedAppDashboardIndexRoute,
  }

const ProtectedSharedAppRouteRouteWithChildren =
  ProtectedSharedAppRouteRoute._addFileChildren(
    ProtectedSharedAppRouteRouteChildren,
  )

interface ProtectedRouteRouteChildren {
  ProtectedAdminRouteRoute: typeof ProtectedAdminRouteRouteWithChildren
  ProtectedDoctorRouteRoute: typeof ProtectedDoctorRouteRouteWithChildren
  ProtectedSharedAppRouteRoute: typeof ProtectedSharedAppRouteRouteWithChildren
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedAdminRouteRoute: ProtectedAdminRouteRouteWithChildren,
  ProtectedDoctorRouteRoute: ProtectedDoctorRouteRouteWithChildren,
  ProtectedSharedAppRouteRoute: ProtectedSharedAppRouteRouteWithChildren,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

interface PublicAuthRouteRouteChildren {
  PublicAuthLoginRoute: typeof PublicAuthLoginRoute
  PublicAuthRegisterDoctorRoute: typeof PublicAuthRegisterDoctorRoute
  PublicAuthRegisterPatientRoute: typeof PublicAuthRegisterPatientRoute
  PublicAuthRegisterIndexRoute: typeof PublicAuthRegisterIndexRoute
}

const PublicAuthRouteRouteChildren: PublicAuthRouteRouteChildren = {
  PublicAuthLoginRoute: PublicAuthLoginRoute,
  PublicAuthRegisterDoctorRoute: PublicAuthRegisterDoctorRoute,
  PublicAuthRegisterPatientRoute: PublicAuthRegisterPatientRoute,
  PublicAuthRegisterIndexRoute: PublicAuthRegisterIndexRoute,
}

const PublicAuthRouteRouteWithChildren = PublicAuthRouteRoute._addFileChildren(
  PublicAuthRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicAuthRouteRoute: typeof PublicAuthRouteRouteWithChildren
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicAuthRouteRoute: PublicAuthRouteRouteWithChildren,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
