/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as ProtectedSettingsRouteImport } from './routes/_protected/settings'
import { Route as ProtectedPlanningRouteImport } from './routes/_protected/planning'
import { Route as ProtectedPatientsRouteImport } from './routes/_protected/patients'
import { Route as ProtectedChatRouteImport } from './routes/_protected/chat'
import { Route as PublicAuthRouteRouteImport } from './routes/_public/_auth/route'
import { Route as PublicAuthLoginRouteImport } from './routes/_public/_auth/login'
import { Route as PublicAuthRegisterIndexRouteImport } from './routes/_public/_auth/register/index'
import { Route as PublicAuthRegisterPatientRouteImport } from './routes/_public/_auth/register/patient'
import { Route as PublicAuthRegisterDoctorRouteImport } from './routes/_public/_auth/register/doctor'

const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedSettingsRoute = ProtectedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedPlanningRoute = ProtectedPlanningRouteImport.update({
  id: '/planning',
  path: '/planning',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedPatientsRoute = ProtectedPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedChatRoute = ProtectedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const PublicAuthRouteRoute = PublicAuthRouteRouteImport.update({
  id: '/_public/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicAuthLoginRoute = PublicAuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicAuthRouteRoute,
} as any)
const PublicAuthRegisterIndexRoute = PublicAuthRegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => PublicAuthRouteRoute,
} as any)
const PublicAuthRegisterPatientRoute =
  PublicAuthRegisterPatientRouteImport.update({
    id: '/register/patient',
    path: '/register/patient',
    getParentRoute: () => PublicAuthRouteRoute,
  } as any)
const PublicAuthRegisterDoctorRoute =
  PublicAuthRegisterDoctorRouteImport.update({
    id: '/register/doctor',
    path: '/register/doctor',
    getParentRoute: () => PublicAuthRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedIndexRoute
  '/chat': typeof ProtectedChatRoute
  '/patients': typeof ProtectedPatientsRoute
  '/planning': typeof ProtectedPlanningRoute
  '/settings': typeof ProtectedSettingsRoute
  '/login': typeof PublicAuthLoginRoute
  '/register/doctor': typeof PublicAuthRegisterDoctorRoute
  '/register/patient': typeof PublicAuthRegisterPatientRoute
  '/register/': typeof PublicAuthRegisterIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof ProtectedIndexRoute
  '/chat': typeof ProtectedChatRoute
  '/patients': typeof ProtectedPatientsRoute
  '/planning': typeof ProtectedPlanningRoute
  '/settings': typeof ProtectedSettingsRoute
  '/login': typeof PublicAuthLoginRoute
  '/register/doctor': typeof PublicAuthRegisterDoctorRoute
  '/register/patient': typeof PublicAuthRegisterPatientRoute
  '/register': typeof PublicAuthRegisterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/_public/_auth': typeof PublicAuthRouteRouteWithChildren
  '/_protected/chat': typeof ProtectedChatRoute
  '/_protected/patients': typeof ProtectedPatientsRoute
  '/_protected/planning': typeof ProtectedPlanningRoute
  '/_protected/settings': typeof ProtectedSettingsRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/_public/_auth/login': typeof PublicAuthLoginRoute
  '/_public/_auth/register/doctor': typeof PublicAuthRegisterDoctorRoute
  '/_public/_auth/register/patient': typeof PublicAuthRegisterPatientRoute
  '/_public/_auth/register/': typeof PublicAuthRegisterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/patients'
    | '/planning'
    | '/settings'
    | '/login'
    | '/register/doctor'
    | '/register/patient'
    | '/register/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/patients'
    | '/planning'
    | '/settings'
    | '/login'
    | '/register/doctor'
    | '/register/patient'
    | '/register'
  id:
    | '__root__'
    | '/_protected'
    | '/_public/_auth'
    | '/_protected/chat'
    | '/_protected/patients'
    | '/_protected/planning'
    | '/_protected/settings'
    | '/_protected/'
    | '/_public/_auth/login'
    | '/_public/_auth/register/doctor'
    | '/_public/_auth/register/patient'
    | '/_public/_auth/register/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  PublicAuthRouteRoute: typeof PublicAuthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/settings': {
      id: '/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/planning': {
      id: '/_protected/planning'
      path: '/planning'
      fullPath: '/planning'
      preLoaderRoute: typeof ProtectedPlanningRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/patients': {
      id: '/_protected/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof ProtectedPatientsRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/chat': {
      id: '/_protected/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ProtectedChatRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_public/_auth': {
      id: '/_public/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicAuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/_auth/login': {
      id: '/_public/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicAuthLoginRouteImport
      parentRoute: typeof PublicAuthRouteRoute
    }
    '/_public/_auth/register/': {
      id: '/_public/_auth/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof PublicAuthRegisterIndexRouteImport
      parentRoute: typeof PublicAuthRouteRoute
    }
    '/_public/_auth/register/patient': {
      id: '/_public/_auth/register/patient'
      path: '/register/patient'
      fullPath: '/register/patient'
      preLoaderRoute: typeof PublicAuthRegisterPatientRouteImport
      parentRoute: typeof PublicAuthRouteRoute
    }
    '/_public/_auth/register/doctor': {
      id: '/_public/_auth/register/doctor'
      path: '/register/doctor'
      fullPath: '/register/doctor'
      preLoaderRoute: typeof PublicAuthRegisterDoctorRouteImport
      parentRoute: typeof PublicAuthRouteRoute
    }
  }
}

interface ProtectedRouteRouteChildren {
  ProtectedChatRoute: typeof ProtectedChatRoute
  ProtectedPatientsRoute: typeof ProtectedPatientsRoute
  ProtectedPlanningRoute: typeof ProtectedPlanningRoute
  ProtectedSettingsRoute: typeof ProtectedSettingsRoute
  ProtectedIndexRoute: typeof ProtectedIndexRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedChatRoute: ProtectedChatRoute,
  ProtectedPatientsRoute: ProtectedPatientsRoute,
  ProtectedPlanningRoute: ProtectedPlanningRoute,
  ProtectedSettingsRoute: ProtectedSettingsRoute,
  ProtectedIndexRoute: ProtectedIndexRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

interface PublicAuthRouteRouteChildren {
  PublicAuthLoginRoute: typeof PublicAuthLoginRoute
  PublicAuthRegisterDoctorRoute: typeof PublicAuthRegisterDoctorRoute
  PublicAuthRegisterPatientRoute: typeof PublicAuthRegisterPatientRoute
  PublicAuthRegisterIndexRoute: typeof PublicAuthRegisterIndexRoute
}

const PublicAuthRouteRouteChildren: PublicAuthRouteRouteChildren = {
  PublicAuthLoginRoute: PublicAuthLoginRoute,
  PublicAuthRegisterDoctorRoute: PublicAuthRegisterDoctorRoute,
  PublicAuthRegisterPatientRoute: PublicAuthRegisterPatientRoute,
  PublicAuthRegisterIndexRoute: PublicAuthRegisterIndexRoute,
}

const PublicAuthRouteRouteWithChildren = PublicAuthRouteRoute._addFileChildren(
  PublicAuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  PublicAuthRouteRoute: PublicAuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
